# 配置文件

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 5240
  useMultipoint: true

# jwt configuration
jwt:
  signingKey: 'wangjie'
  expiresTime: 604800
  bufferTime: 86400
  issuer: 'wangjie'

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[Magic Admin]'
  director: 'log'
  showLine: true
  encodeLevel: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  logInConsole: true

# redis configuration
redis:
  addr: '127.0.0.1:6379'
  # addr: '172.24.0.11:6379' # 容器
  password: ''
  db: 0

# mysql connect configuration
mysql:
  path: '127.0.0.1'
  # path: '172.24.0.10' # 容器
  config: 'charset=utf8mb4&parseTime=true'
  dbName: 'dbMagicAdmin'
  userName: 'root'
  password: 'root'
  maxidleConns: 10
  maxOpenConns: 100
  timeout: 28800
  logMode: ""
  logZap: false

# timer task db clear table
Timer:
  start: true
  spec: "@daily"  # 定时任务详细配置参考 https://pkg.go.dev/github.com/robfig/cron/v3
  detail: [
    # tableName: 需要清理的表名
    # compareField: 需要比较时间的字段
    # interval: 时间间隔, 具体配置详看 time.ParseDuration() 中字符串表示 且不能为负数
    # 2160h = 24 * 30 * 3 -> 三个月
    { tableName: "sys_operation_records" , compareField: "createdAt", interval: "2160h" },
    { tableName: "jwt_blacklists" , compareField: "createdAt", interval: "168h" }
    #{ tableName: "log2" , compareField: "created_at", interval: "2160h" }
  ]

