version: "3.7"

services:
  mysql:
    image: mysql
    hostname: mysql
    container_name: mysql
    ports:
      - 3306:3306
    networks:
      magicAdmin:
        ipv4_address: 172.24.0.10
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis
    restart: always
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      magicAdmin:
        ipv4_address: 172.24.0.11
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis/logs:/logs
    command: ["redis-server","/etc/redis/redis.conf"]
  server:
    build: ../server
    hostname: magicAdminServer
    container_name: magicAdminServer
    # restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "5241:5240"
    networks:
      magicAdmin:
        ipv4_address: 172.24.0.19
    volumes:
      - ../server:/go/src/magicAdmin

networks:
  magicAdmin:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16